package com.github.lol4fun.core.model

import android.os.Parcelable
import kotlinx.android.parcel.Parcelize

@Parcelize
data class ParticipantStats(
    val id: Int,
    val win: Boolean,
    val champLevel: Int,
    val firstTowerKill: Boolean,
    val firstTowerAssist: Boolean,
    val firstBloodKill: Boolean,
    val firstBloodAssist: Boolean,
    val firstInhibitorKill: Boolean,
    val firstInhibitorAssist: Boolean,
    val visionScore: Long,
    val magicDamageDealtToChampions: Long,
    val physicalDamageDealtToChampions: Long,
    val damageDealtToObjectives: Long,
    val damageDealtToTurrets: Long,
    val magicDamageDealt: Long,
    val physicalDamageDealt: Long,
    val damageSelfMitigated: Long,
    val magicalDamageTaken: Long,
    val trueDamageTaken: Long,
    val trueDamageDealtToChampions: Long,
    val physicalDamageTaken: Long,
    val trueDamageDealt: Long,
    val totalDamageTaken: Long,
    val totalDamageDealt: Long,
    val totalDamageDealtToChampions: Long,
    val timeCCingOthers: Long,
    val totalTimeCrowdControlDealt: Int,
    val longestTimeSpentLiving: Int,
    val nodeNeutralizeAssist: Int,
    val nodeCapture: Int,
    val nodeCaptureAssist: Int,
    val nodeNeutralize: Int,
    val kills: Int,
    val deaths: Int,
    val assists: Int,
    val totalMinionsKilled: Int,
    val totalUnitsHealed: Int,
    val totalHeal: Long,
    val wardsKilled: Int,
    val wardsPlaced: Int,
    val turretKills: Int,
    val totalScoreRank: Int,
    val neutralMinionsKilled: Int,
    val killingSprees: Int,
    val unrealKills: Int,
    val doubleKills: Int,
    val tripleKills: Int,
    val quadraKills: Int,
    val pentaKills: Int,
    val largestMultiKill: Int,
    val largestCriticalStrike: Int,
    val largestKillingSpree: Int,
    val inhibitorKills: Int,
    val teamObjective: Int,
    val combatPlayerScore: Int,
    val goldSpent: Int,
    val goldEarned: Int,
    val objectivePlayerScore: Int,
    val totalPlayerScore: Int,
    val neutralMinionsKilledTeamJungle: Int,
    val neutralMinionsKilledEnemyJungle: Int,
    val sightWardsBoughtInGame: Int,
    val altarsCaptured: Int,
    val altarsNeutralized: Int,
    val visionWardsBoughtInGame: Int,
    val item0: Int,
    val item1: Int,
    val item2: Int,
    val item3: Int,
    val item4: Int,
    val item5: Int,
    val item6: Int,
    val playerScore0: Int,
    val playerScore1: Int,
    val playerScore2: Int,
    val playerScore3: Int,
    val playerScore4: Int,
    val playerScore5: Int,
    val playerScore6: Int,
    val playerScore7: Int,
    val playerScore8: Int,
    val playerScore9: Int,
    val perkPrimaryStyle: Int,  //Primary rune path
    val perkSubStyle: Int,      //Secondary rune path
    val perk0: Int,             //Primary path keystone rune.
    val perk1: Int,             //Primary path rune.
    val perk2: Int,
    val perk3: Int,
    val perk4: Int,             //Secondary path rune.
    val perk5: Int,
    val perk0Var1: Int,         //Post game rune stats.
    val perk0Var2: Int,
    val perk0Var3: Int,
    val perk1Var1: Int,
    val perk1Var2: Int,
    val perk1Var3: Int,
    val perk2Var1: Int,
    val perk2Var2: Int,
    val perk2Var3: Int,
    val perk3Var1: Int,
    val perk3Var2: Int,
    val perk3Var3: Int,
    val perk4Var1: Int,
    val perk4Var2: Int,
    val perk4Var3: Int,
    val perk5Var1: Int,
    val perk5Var2: Int,
    val perk5Var3: Int
): Parcelable